### ISSUE TITLE
Does not work with Velocity

### ISSUE THREAD

**Issue by gwhobbs** [grigio/meteor-babel#28]
When this package (or another Babel npm package I tried) is installed, the Velocity testing package fails to load.  

```
I20150629-16:44:24.817(-5)? Exception in callback of async function: Error: Match error: Expected Number in field port
I20150629-16:44:24.817(-5)?     at checkSubtree (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/check.js:270:11)
I20150629-16:44:24.817(-5)?     at /Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/check.js:311:9
I20150629-16:44:24.817(-5)?     at Function._.each._.forEach (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/underscore.js:147:22)
I20150629-16:44:24.817(-5)?     at checkSubtree (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/check.js:308:5)
I20150629-16:44:24.817(-5)?     at check (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/check.js:50:5)
I20150629-16:44:24.817(-5)?     at [object Object].Meteor.methods.velocity/mirrors/init (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/velocity_core.js:1202:7)
I20150629-16:44:24.817(-5)?     at maybeAuditArgumentChecks (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
I20150629-16:44:24.818(-5)?     at /Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/ddp.js:2358:18
I20150629-16:44:24.818(-5)?     at [object Object]._.extend.withValue (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150629-16:44:24.818(-5)?     at [object Object]._.extend.apply (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/ddp.js:2357:45)
I20150629-16:44:24.818(-5)?     at [object Object]._.extend.call (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/ddp.js:2300:17)
I20150629-16:44:24.818(-5)?     at _startMirror (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/velocity_core.js:1398:12)
I20150629-16:44:24.818(-5)?     at /Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/velocity_core.js:1301:9
I20150629-16:44:24.818(-5)?     at runWithEnvironment (/Users/ghobbs/MeteorApp/.meteor/local/build/programs/server/packages/meteor.js:1041:24)
```

**Comment by grigio** [comment]
`Error: Match error: Expected Number in field port` it could be related to https://github.com/grigio/meteor-babel/issues/5
